### PR TITLE
Disable StrictHostKeyChecking

### PR DESCRIPTION
**Pull request by maximeaubaret**

### CODE REVIEW

**Comment by cedricziel** [comment]
That's a very bad idea as it essentially allows any man in the middle to intercept.

**Comment by maximeaubaret** [comment]
Yes, now that I think of it you're right. 

How do you go about authorizing a key then?

**Comment by cedricziel** [comment]
There's a plugin for that :)

https://github.com/cedricziel/dokku-hostkeys-plugin

Please check the dokku-04 branch

**Comment by maximeaubaret** [comment]
Nice! Thanks @cedricziel ;)

**Pull request closed without merging**
