### PR TITLE
Upgrade plugin for usage with 0.4.x

### PR DESCRIPTION
**Pull request by josegonzalez**

### CODE REVIEW

**Comment by josegonzalez** [comment]
*bump*

**Comment by josegonzalez** [comment]
This should also take care of #10.

**Comment by cedricziel** [comment]
Sure-It's just that I like to merge all pull-requests if possible, so everyone get's a little karma. (I think you're referencing your other patch over at the hostkeys plugin.)

**Comment by josegonzalez** [comment]
Yeah just trying to bump this one/any of them, since they've been sitting here for a while ;)

**Comment by cedricziel** [comment]
I'm at the manual merge, then testing it all together :)

**Comment by cedricziel** [comment]
Alright, merged. Let the testing begin. Thanks a bunch!

**Pull request merged**
