### PR TITLE
DOC: added host-keys plugin to requirements

### LINKED ISSUE #15: pip install from private repo
Hey, i tried using this plugin to be able to do a pip install from a private git repo but its not working.
the output is as follows:
```
$ pip install -r requirements.txt
       Collecting datapy from git+ssh://git@github.com/***/***#egg=*** (from -r requirements.txt (line 15))
       Cloning ssh://git@github.com/***/*** to /tmp/pip-build-pjt3em88/***
remote: ost key verification failed.
       fatal: Could not read from remote repository.

       Please make sure you have the correct access rights
       and the repository exists.
       Command "git clone -q ssh://git@github.com/***/*** /tmp/pip-build-pjt3em88/***" failed with error code 128 in None
To dokku@***:***
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'dokku@***:***'
```

any idea what can be the problem?

/cc @yoavram

### PR DESCRIPTION
**Pull request by yoavram**
This fixes #15 by explicitly stating a requirement plugin.
/cc @maticrivo

### CODE REVIEW

**Comment by cedricziel** [comment]
It's no strict requirement-could you add something like "optional but highlyy recommended"?

Thank you!

**Comment by cedricziel** [comment]
Also, I initially added a similar hint to the README (https://github.com/cedricziel/dokku-deployment-keys#ssh-deployment-keys-plugin-for-dokku-) do you think that's not enough?

**Comment by yoavram** [comment]
Oh, that's enough, only maybe move it to the requirements section?

**Comment by cedricziel** [comment]
Great, can you amend the PR?

**Comment by cedricziel** [comment]
Great - thank you for your efforts! :)

**Comment by yoavram** [comment]
Thanks you for the plugins!

**Pull request merged**
